version: '3.8'

services:
  web:
    build: .
    command: sh -c "python manage.py collectstatic --noinput && python manage.py compress --force && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A core beat --loglevel=info
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
