# Generated by Django 5.0.6 on 2024-11-12 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='заголовок')),
            ],
            options={
                'verbose_name': "заголовок для страницы 'Автоподбор'",
                'verbose_name_plural': "заголовки для страницы 'Автоподбор'",
            },
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='название')),
                ('description', models.TextField(null=True, verbose_name='описание')),
                ('price', models.CharField(max_length=100, null=True, verbose_name='стоимость')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selection.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': "данные к странице 'Автоподбор'",
                'verbose_name_plural': "данные к странице 'Автоподбор'",
            },
        ),
    ]
