# Generated by Django 5.0.6 on 2024-10-23 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Названия типо кузова')),
            ],
            options={
                'verbose_name': 'Тип кузовова',
                'verbose_name_plural': 'Типы кузова',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название цвета')),
            ],
            options={
                'verbose_name': 'Цвет для машины',
                'verbose_name_plural': 'Цвета для машин',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100, verbose_name='Дата парсинга')),
                ('usd', models.FloatField(blank=True, default=None, null=True, verbose_name='USD')),
                ('eur', models.FloatField(blank=True, default=None, null=True, verbose_name='EUR')),
                ('jpy', models.FloatField(blank=True, default=None, null=True, verbose_name='JPY')),
                ('krw', models.FloatField(blank=True, default=None, null=True, verbose_name='KRW')),
                ('cny', models.FloatField(blank=True, default=None, null=True, verbose_name='CNY')),
            ],
            options={
                'verbose_name': 'Валюты',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название привода')),
            ],
            options={
                'verbose_name': 'Тип привода',
                'verbose_name_plural': 'Типы приводов',
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Завяка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='PhotoCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
            ],
            options={
                'verbose_name': 'Фото машины',
                'verbose_name_plural': 'Фото машин',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя Фамилия')),
                ('text_review', models.TextField(verbose_name='Коментарий пользователя')),
                ('icon_user', models.ImageField(null=True, upload_to='user/phoro_user', verbose_name='Фотографии пользователя')),
                ('reviews_date', models.DateField(help_text='Уже загруженные фотографии не нужно добовлять заново', verbose_name='Дата отзыва')),
                ('num_view', models.IntegerField(default=0, help_text='Каким по очереди отображать?', verbose_name='Номер отображения')),
                ('image1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Фотография к отзыву 1')),
                ('image2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Фотография к отзыву 2')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='КПП название')),
            ],
            options={
                'verbose_name': 'Тип КПП',
                'verbose_name_plural': 'Типы КПП',
            },
        ),
        migrations.CreateModel(
            name='TypeEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип двигателя ( значение )')),
            ],
            options={
                'verbose_name': 'Тип двигателя',
                'verbose_name_plural': 'Типы двигателя',
            },
        ),
        migrations.CreateModel(
            name='UniqueColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Элемент')),
                ('type_of_unique', models.CharField(default='', max_length=100, verbose_name='Тип')),
                ('table', models.CharField(default='', max_length=100, verbose_name='Таблица')),
            ],
            options={
                'verbose_name': 'Уникальные цвета авто',
                'verbose_name_plural': 'Уникальные цвета авто',
            },
        ),
        migrations.CreateModel(
            name='CarMainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Впишите название бренда', max_length=100, verbose_name='Бренд')),
                ('model', models.CharField(help_text='Впишите название модели', max_length=150, verbose_name='Модель')),
                ('year', models.IntegerField(help_text='Впишите год автомабиля', verbose_name='Год')),
                ('engine_volume', models.IntegerField(help_text='Впишите объяем двигателя', verbose_name='Объяем двигателя')),
                ('mileage', models.IntegerField()),
                ('price', models.IntegerField()),
                ('body_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.bodytype', verbose_name='Тип кузова')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.color', verbose_name='Цвет')),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.drive', verbose_name='Тип привода')),
                ('photos', models.ManyToManyField(null=True, to='cars.photocars', verbose_name='Фотографии авто')),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.transmission', verbose_name='Тип КПП')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.typeengine', verbose_name='Тип двигателя')),
            ],
            options={
                'verbose_name': 'Авто Главная Страница',
                'verbose_name_plural': 'Авто Главная Страница',
            },
        ),
        migrations.CreateModel(
            name='CarKorea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Впишите название бренда', max_length=100, verbose_name='Бренд')),
                ('model', models.CharField(help_text='Впишите название модели', max_length=150, verbose_name='Модель')),
                ('year', models.IntegerField(help_text='Впишите год автомабиля', verbose_name='Год')),
                ('engine_volume', models.IntegerField(help_text='Впишите объяем двигателя', verbose_name='Объяем двигателя')),
                ('mileage', models.IntegerField()),
                ('price', models.IntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.color', verbose_name='Цвет')),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.drive', verbose_name='Тип привода')),
                ('photos', models.ManyToManyField(null=True, to='cars.photocars', verbose_name='Фотографии авто')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.typeengine', verbose_name='Тип двигателя')),
            ],
            options={
                'verbose_name': 'Авто Корея',
                'verbose_name_plural': 'Авто Корея',
            },
        ),
        migrations.CreateModel(
            name='CarJapan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(help_text='Параметр нельзя менять', max_length=100, verbose_name='ID в API')),
                ('brand', models.CharField(help_text='Впишите название бренда', max_length=100, verbose_name='Бренд')),
                ('model', models.CharField(help_text='Впишите название модели', max_length=150, verbose_name='Модель')),
                ('year', models.IntegerField(help_text='Впишите год автомабиля', verbose_name='Год')),
                ('engine_volume', models.IntegerField(help_text='Впишите объяем двигателя', verbose_name='Объяем двигателя')),
                ('mileage', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('body_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.bodytype', verbose_name='Тип кузова')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.color', verbose_name='Цвет')),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.drive', verbose_name='Тип привода')),
                ('photos', models.ManyToManyField(null=True, to='cars.photocars', verbose_name='Фотографии авто')),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.transmission', verbose_name='Тип КПП')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.typeengine', verbose_name='Тип двигателя')),
            ],
            options={
                'verbose_name': 'Авто Япония',
                'verbose_name_plural': 'Авто Япония',
            },
        ),
        migrations.CreateModel(
            name='CarChina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(help_text='Параметр нельзя менять', max_length=100, verbose_name='ID в API')),
                ('brand', models.CharField(help_text='Впишите название бренда', max_length=100, verbose_name='Бренд')),
                ('model', models.CharField(help_text='Впишите название модели', max_length=150, verbose_name='Модель')),
                ('year', models.IntegerField(help_text='Впишите год автомабиля', verbose_name='Год')),
                ('engine_volume', models.IntegerField(help_text='Впишите объяем двигателя', verbose_name='Объяем двигателя')),
                ('mileage', models.IntegerField()),
                ('price', models.IntegerField()),
                ('body_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.bodytype', verbose_name='Тип кузова')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.color', verbose_name='Цвет')),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.drive', verbose_name='Тип привода')),
                ('photos', models.ManyToManyField(null=True, to='cars.photocars', verbose_name='Фотографии авто')),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.transmission', verbose_name='Тип КПП')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.typeengine', verbose_name='Тип двигателя')),
            ],
            options={
                'verbose_name': 'Авто Китай',
                'verbose_name_plural': 'Авто Китай',
            },
        ),
    ]
