# Generated by Django 5.0.6 on 2024-10-23 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_feedback_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='number',
            field=models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(16)], verbose_name='Номер телефона'),
        ),
    ]
