# Generated by Django 5.0.6 on 2024-10-24 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_feedback_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='country',
            field=models.CharField(default='Япония', max_length=100, verbose_name='Страна'),
        ),
        migrations.CreateModel(
            name='ColorTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='максимальная длина 255 символов', max_length=255, verbose_name='название')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='cars.color', verbose_name='цвет')),
            ],
        ),
    ]
