# Generated by Django 5.0.6 on 2024-10-24 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_carmark_carmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='carmark',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Страна'),
        ),
        migrations.CreateModel(
            name='PrivodTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='максимальная длина 255 символов', max_length=255, verbose_name='название')),
                ('privod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='cars.privod', verbose_name='цвет')),
            ],
        ),
    ]
