# Generated by Django 5.0.6 on 2024-10-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_alter_colortag_color_alter_privodtag_privod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basefilter',
            name='marka_name',
            field=models.TextField(blank=True, help_text='исключаем эти марки, несколько значений разделяются запятой', null=True, verbose_name='марки автомобиля'),
        ),
        migrations.AlterField(
            model_name='basefilter',
            name='priv',
            field=models.TextField(blank=True, help_text='исключаем эти приводы, несколько значений разделяются запятой', null=True, verbose_name='привод автомобиля'),
        ),
    ]
