# Generated by Django 5.0.6 on 2024-10-27 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_alter_basefilter_marka_name_alter_basefilter_priv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmainpage',
            name='body_type',
        ),
        migrations.RemoveField(
            model_name='carchina',
            name='body_type',
        ),
        migrations.RemoveField(
            model_name='carjapan',
            name='body_type',
        ),
        migrations.RemoveField(
            model_name='carchina',
            name='color',
        ),
        migrations.RemoveField(
            model_name='carchina',
            name='drive',
        ),
        migrations.RemoveField(
            model_name='carchina',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='carchina',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='carchina',
            name='transmission',
        ),
        migrations.RemoveField(
            model_name='carjapan',
            name='color',
        ),
        migrations.RemoveField(
            model_name='carjapan',
            name='drive',
        ),
        migrations.RemoveField(
            model_name='carjapan',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='carjapan',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='carjapan',
            name='transmission',
        ),
        migrations.RemoveField(
            model_name='carkorea',
            name='color',
        ),
        migrations.RemoveField(
            model_name='carkorea',
            name='drive',
        ),
        migrations.RemoveField(
            model_name='carkorea',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='carkorea',
            name='photos',
        ),
        migrations.AlterField(
            model_name='carmainpage',
            name='drive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.privod', verbose_name='Тип привода'),
        ),
        migrations.AlterField(
            model_name='carmainpage',
            name='transmission',
            field=models.CharField(help_text='Автомат или Механика', max_length=150, verbose_name='Тип КПП'),
        ),
        migrations.RemoveField(
            model_name='carmainpage',
            name='fuel_type',
        ),
        migrations.DeleteModel(
            name='UniqueColor',
        ),
        migrations.AlterModelOptions(
            name='carmark',
            options={'verbose_name': 'Уникальные марки авто', 'verbose_name_plural': 'Уникальные марки авто'},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'Уникальные модели авто', 'verbose_name_plural': 'Уникальные модели авто'},
        ),
        migrations.AlterModelOptions(
            name='colortag',
            options={'verbose_name': 'Тег для цвета', 'verbose_name_plural': 'Теги для цветов'},
        ),
        migrations.AlterModelOptions(
            name='privod',
            options={'verbose_name': 'Привод авто', 'verbose_name_plural': 'Приводы авто'},
        ),
        migrations.AlterModelOptions(
            name='privodtag',
            options={'verbose_name': 'Тег для привода', 'verbose_name_plural': 'Теги для приводов'},
        ),
        migrations.DeleteModel(
            name='BodyType',
        ),
        migrations.DeleteModel(
            name='CarChina',
        ),
        migrations.DeleteModel(
            name='CarJapan',
        ),
        migrations.DeleteModel(
            name='CarKorea',
        ),
        migrations.DeleteModel(
            name='Drive',
        ),
        migrations.DeleteModel(
            name='Transmission',
        ),
        migrations.DeleteModel(
            name='TypeEngine',
        ),
    ]
