# Generated by Django 5.0.6 on 2024-10-27 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_alter_reviews_reviews_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='reviews_date',
        ),
    ]
