# Generated by Django 5.0.6 on 2024-10-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_remove_reviews_reviews_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='icon_user',
            field=models.ImageField(default='user/phoro_user/0c3c22da-32c9-11ef-a698-31ca6a59cdec.webp', null=True, upload_to='user/phoro_user', verbose_name='Фотографии пользователя'),
        ),
    ]
