# Generated by Django 5.0.6 on 2024-11-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0020_alter_reviews_icon_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='basefilter',
            name='max_eng_v',
            field=models.DecimalField(decimal_places=1, default=5, help_text='меньше или равно какого значения (л)', max_digits=3, verbose_name='максимальный объем двигателя'),
        ),
    ]
