# Generated by Django 5.0.6 on 2024-11-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0022_bodytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorMainPageCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='цвет')),
            ],
            options={
                'verbose_name': 'цвет для популярных машин',
                'verbose_name_plural': 'цвета для популярных машин',
            },
        ),
    ]
