# Generated by Django 5.0.6 on 2024-11-10 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0025_transmission_typeengine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmainpage',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.colormainpagecars', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='carmainpage',
            name='drive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.drive', verbose_name='Тип привода'),
        ),
        migrations.AlterField(
            model_name='carmainpage',
            name='transmission',
            field=models.ForeignKey(help_text='Впишите тип КПП', on_delete=django.db.models.deletion.CASCADE, to='cars.transmission', verbose_name='Тип КПП'),
        ),
    ]
