# Generated by Django 5.0.6 on 2024-11-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='gis',
            field=models.URLField(null=True, verbose_name='2GIS'),
        ),
        migrations.AddField(
            model_name='about',
            name='yandex_map',
            field=models.URLField(null=True, verbose_name='яндекс карты'),
        ),
        migrations.AlterField(
            model_name='about',
            name='address',
            field=models.TextField(verbose_name='адрес офиса'),
        ),
        migrations.AlterField(
            model_name='about',
            name='denomination',
            field=models.TextField(verbose_name='наименование'),
        ),
    ]
